version: '2'

services:
  postgresql:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: rental_password
      POSTGRES_USER: rental_user
      POSTGRES_DB: rental
    ports:
      - '5432:5432'
  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - '5050:5050'
      - '85:80'
    links:
      - postgresql:postgresql
    depends_on:
      - postgresql
    environment:
      PGADMIN_DEFAULT_EMAIL: rental@rental.com
      PGADMIN_DEFAULT_PASSWORD: rental
